#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 24 21:50:01 2020

@author: ihsong
"""


from __future__ import unicode_literals
import os
import requests
from pprint import pprint
from bs4 import BeautifulSoup



# episode_url = 'http://cartoon.media.daum.net/webtoon/viewer/72778'
# lxml = requests.get(episode_url).text
# soup = BeautifulSoup(lxml, 'lxml-xml')

# comic_title = soup.select('.list_info dd')
# print(comic_title)

# comic_title= soup.select('.txt_title a')

# B = soup.find_all('a', class_ ='link_title')
# print(B.get_text()) 
# B = soup.find('a', class_ ='link_title')
# print(B.get_()) 


episode_url = 'http://cartoon.media.daum.net/webtoon/viewer/72779'
html = requests.get(episode_url)
soup = BeautifulSoup(html.text, 'lxml-xml')
html.close()
data1 = soup.find('a',{'class':'link_title'})
# data1 = soup.find('ul',{'id':'dayList1','class':'list_wt'})
pprint(data1)

data2 = soup.find('dl',{'class':'list_info'})

print(data2.find('dd',{'class':'txt_episode'}))

# comic_title = ' '.join(soup.select('.list_info a')[0].text.split()) # ' '.join(['마음의소리', '조석'])
# ep_title = ' '.join(soup.select('.tit_area h3')[0].text.split())

# for img_tag in soup.select('.wt_viewer img'):
#     image_file_url = img_tag['src']
#     image_dir_path = os.path.join(os.path.dirname(__file__), comic_title, ep_title)
#     image_file_path = os.path.join(image_dir_path, os.path.basename(image_file_url))

#     if not os.path.exists(image_dir_path):
#         os.makedirs(image_dir_path)

#     print(image_file_path)

#     headers = {'Referer': episode_url}
#     image_file_data = requests.get(image_file_url, headers=headers).content
#     print(type(image_file_data))
#     print(len(image_file_data))
#     open(image_file_path, 'wb').write(image_file_data)

# print('Completed !')

    
    

    